
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.*;
import java.awt.print.*;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fnuke
 */
public class Payment extends javax.swing.JFrame {
private static Scanner x;
private static Scanner b;
public double surplus;
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
       checkbirthday();
          this.setExtendedState(JFrame.MAXIMIZED_BOTH);
          
        initiliaseTable();
        initiliaseCost();
    }
public void initiliaseTable() {
    String filepath = "order.txt";
        File file = new File(filepath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
              
            DefaultTableModel model = (DefaultTableModel)jTablePayment.getModel();
            Object[] lines = br.lines().toArray();
            for(int i =0; i<lines.length;i++) {
                
                String[] row = lines[i].toString().split(",");
                if(row[0].contains(Login.user)) {
                model.addRow(row);
                }
                
               
                }
br.close();
        } 
        catch (IOException ex) {
            System.out.println("Error");
            }
    
    
}
    
public void initiliaseCost() {
    double total =0;
    double finaltotal =0;
    double quantity=0;
    double cost =0;
    double fragile = 5;
    double nonfragile = 2;
    DecimalFormat df = new DecimalFormat(".00");
    double discount = 0.85;
     try {
            
            for(int i = 0;i< jTablePayment.getRowCount(); i++)
            {
                cost= Double.parseDouble((String) jTablePayment.getValueAt(i,3));
               
                  quantity= Double.parseDouble((String) jTablePayment.getValueAt(i,4));   
                  
                  
                  if (jTablePayment.getValueAt(i,2).equals("Fragile")){
            total= cost  * quantity+ fragile;
                  }
                  else if(jTablePayment.getValueAt(i,2).equals("Non-Fragile"))
                  { total= cost  * quantity+ nonfragile;
                  
                  }
                  
                  
            finaltotal=finaltotal+total;
                             
}   
            if(jLabel5.getText()==("It's your birthday!! You are getting 15% discount on checkout!")){
                 finaltotal=finaltotal*discount;
              
                 jTextFieldCost.setText(df.format(finaltotal));
            }
            else {
               
                jTextFieldCost.setText(df.format(finaltotal));
            }
             
    
           
        
            
            
        } catch (Exception ex) {
           System.out.println("Error");
        }
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePayment = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPay = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Product", "Fragility", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTablePayment);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Total Cost:");

        jTextFieldCost.setEditable(false);
        jTextFieldCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pay:");

        jTextFieldPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPayActionPerformed(evt);
            }
        });
        jTextFieldPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPayKeyTyped(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Back to Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Update Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Back To Order Page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("RM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("RM");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fragile Product's packaging cost: RM 5.00");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Non-Fragile Product's packaging cost: RM 2.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1044, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(69, 69, 69)
                .addComponent(jButton4)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jButton2)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(53, 53, 53))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Double pay,money,shor;
        pay=Double.parseDouble(jTextFieldCost.getText());
      money = Double.parseDouble(jTextFieldPay.getText());
      surplus=money-pay;
      shor=pay-money;
      if(pay.equals(.00))
      {
           JOptionPane.showMessageDialog(null,"No Product is in cart ","Failed Payment", JOptionPane.ERROR_MESSAGE);
      }
      
      else if (surplus<0)
      {     DecimalFormat df = new DecimalFormat(".00");
          JOptionPane.showMessageDialog(null,"Payment is not enough, you are RM "+ df.format(shor)+" short","Failed Payment", JOptionPane.ERROR_MESSAGE);
      }
      
      else{
          DecimalFormat df = new DecimalFormat(".00");
             JOptionPane.showMessageDialog(null,"Payment Successful, your change is RM "+df.format(surplus),"Your payment is successful", JOptionPane.INFORMATION_MESSAGE);
     
      removeOrder();
     
      printbill(jTextFieldCost.getText());
      CustomerMenu as = new CustomerMenu();
      as.setVisible(true);
      this.setVisible(false);
       
     
      }
                            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPayActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CustomerMenu da = new CustomerMenu();
        da.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CustomerProducts co = new CustomerProducts();
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateOrder();
        initiliaseCost();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTablePayment.getModel();
        try {
            int SelectedRowIndex = jTablePayment.getSelectedRow();
            model.removeRow(SelectedRowIndex);
            
        } catch(Exception ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostActionPerformed

    private void jTextFieldPayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPayKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
if(Character.isLetter(c)&&!evt.isAltDown())
    evt.consume();
    }//GEN-LAST:event_jTextFieldPayKeyTyped
 public void removeOrder()
{
 
  File f1 = new File("order.txt");
  File f2 = new File("tempfile.txt");
  String name = "";
  String product = "";
  String fragility = "";
  String price="";
   String quantity= "";
  try 
           {
               FileWriter fw = new FileWriter("tempfile.txt",true);
               BufferedWriter bw = new BufferedWriter(fw);
               PrintWriter pw = new PrintWriter(bw);
                FileWriter zw = new FileWriter("paidorder.txt",true);
               BufferedWriter xw = new BufferedWriter(zw);
               PrintWriter cw = new PrintWriter(xw);
               x = new Scanner(new File("order.txt"));
               x.useDelimiter("[,\n]");
               
               while(x.hasNext())
               {
                   name=x.next();
                   product=x.next();
                   fragility=x.next();
                   price=x.next();
                   quantity=x.next();
                   if( !name.equals(Login.user) )
                   {
                               pw.print(name + "," + product + ","+fragility+","+price+","+quantity);
                              
                            
                   }
                   else {
                        cw.print(name + "," + product + ","+fragility+","+price+","+quantity);
                   }
                  
                    
               }
               x.close();
               pw.flush();
               pw.close();
               cw.flush();
               cw.close();
               f1.delete();
               File dump = new File("order.txt");
               f2.renameTo(dump);
                
           }
           
          catch (IOException e)
                   {
                       System.out.println("Error");
                   }
}
 public void updateOrder() {
            File f1 = new File("order.txt");
            File f2 = new File("temp.txt");
            String name = "";
            String product = "";
            String fragility = "";
            String price="";
            String quantity= "";
            try {
                FileWriter fw = new FileWriter("temp.txt",true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter pw = new PrintWriter(bw);  
                x = new Scanner(new File("order.txt"));
                x.useDelimiter("[,\n]");
              for(int i = 0;i< jTablePayment.getRowCount(); i++) {
                pw.println(jTablePayment.getValueAt(i,0).toString()+","+jTablePayment.getValueAt(i,1).toString()+","+jTablePayment.getValueAt(i,2).toString()+","+jTablePayment.getValueAt(i,3).toString()+","+jTablePayment.getValueAt(i,4));
       
                       
                   }  
                while (x.hasNext()) {
                    name=x.next();
                   product=x.next();
                   fragility=x.next();
                   price=x.next();
                   quantity=x.next();
                   
                   if (!name.equals(Login.user)) 
                   {
                         pw.print(name + "," + product + ","+fragility+","+price+","+quantity);
                   }
                  
                   }
                
               
           
                 x.close();
                pw.flush();
                  pw.close();
                f1.delete();
               File dump = new File("order.txt");
               f2.renameTo(dump);
               JOptionPane.showMessageDialog(null,"Your orders are updated!","Success", JOptionPane.INFORMATION_MESSAGE);
 } 
        catch (Exception ex) {
            System.out.println("Error");
            }
}
 public void printbill(String cost)  {
     MessageFormat header = new MessageFormat("Your Receipt");
 DecimalFormat df = new DecimalFormat(".00");
           MessageFormat footer = new MessageFormat("Total Cost is RM: "+cost +" You Paid RM: "+ jTextFieldPay.getText()+" Your change is RM: "+df.format(surplus));
        try {
            
           jTablePayment.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch (Exception e )
        {
            System.out.println(e);
        }
}
 
 
 public void checkbirthday() {
      String tempUser = "";
        String tempName = "";
        
        String tempid="";
        String tempdate="";
        String tempAddress ="";
        String tempNumber="";
            Date dates = new Date();
          DateFormat fmt = new SimpleDateFormat("dd MMMMMMMMMM");
         
          String date = fmt.format(dates);
        
         try
        {
            b = new Scanner(new File("profile.txt"));
            b.useDelimiter("[,\n]");
            while (b.hasNext())
            {
                tempUser = b.next();
                tempName = b.next();
                tempid=b.next();
                tempdate=b.next();
                tempAddress = b.next();
                tempNumber=b.next();
                
                if(tempUser.trim().equals(Login.user.trim()))
                {
                   if (date.equals(tempdate)) {
                          
                       jLabel5.setText("It's your birthday!! You are getting 15% discount on checkout!");
                   }
                   else {
                       
                   }
                }   
            }
            b.close();
        }
                     catch(Exception e)
                        {
                        System.out.println("Error");
                        }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePayment;
    private javax.swing.JTextField jTextFieldCost;
    private javax.swing.JTextField jTextFieldPay;
    // End of variables declaration//GEN-END:variables
}
